common:
  aws_region: "us-east-1"
  key_name: "demo-key"         # 請填入你在 AWS 上的 Key Pair 名稱
  instance_type: "t2.micro"

servers:
  dev_server:
    env: "Dev"
    admin: "Ian (開發部)"
  qa_server:
    env: "QA"
    admin: "Winliam (測試部)"