---
plugin: amazon.aws.aws_ec2

regions:
  - us-east-1

filters:
  instance-state-name: running

compose:
  ansible_host: public_ip_address
  ansible_user: "'ec2-user'"
  server: "{ 'env': tags.Environment, 'admin': tags.Admin }"


# 核心功能：透過 Tag 自動分組 (Group by Tags)
keyed_groups:
  - key: tags.Environment
    prefix: env